# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "53f5e8236be0d49ab596ea9e1d3c770d"
name = "intl-app"
application_url = "https://limiting-baby-westminster-bradford.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_products,read_translations,write_translations,read_locales,write_locales,read_content,read_online_store_pages,read_themes"

[auth]
redirect_urls = [
  "https://limiting-baby-westminster-bradford.trycloudflare.com/auth/callback",
  "https://limiting-baby-westminster-bradford.trycloudflare.com/auth/shopify/callback",
  "https://limiting-baby-westminster-bradford.trycloudflare.com/api/auth/callback"
]
